using System.IO;
using UnityEditor;
using UnityEngine;

namespace Pets.EditorTools
{
    /// <summary>Import settings for full-screen backdrops under Assets/Art/Backgrounds (the battle
    /// screen's BattleForest.png, generated by tools/generate_battle_background.py), applied from
    /// code like every other art folder.
    ///
    /// Pixel art authored at half the canvas resolution, so Point filtering (each source pixel a
    /// crisp 2x2 block, not a blur) and no compression (block compression smears its hard colour
    /// edges — one 640x360 texture uncompressed is under a megabyte). No mipmaps: it's drawn at
    /// least 1:1, never minified.
    ///
    /// Deliberately **not** packed into an atlas by SpriteAtlasBuilder: a backdrop is one image
    /// drawn once behind everything, so atlasing it saves no draw calls and would only bloat
    /// whichever atlas it joined.</summary>
    public sealed class BackgroundImportProcessor : AssetPostprocessor
    {
        private const string FolderPrefix = "Assets/Art/Backgrounds/";

        private void OnPreprocessTexture()
        {
            if (!assetPath.StartsWith(FolderPrefix) || Path.GetExtension(assetPath) != ".png")
            {
                return;
            }

            var importer = (TextureImporter)assetImporter;
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.spritePixelsPerUnit = 100f;
            importer.mipmapEnabled = false;
            importer.filterMode = FilterMode.Point;
            importer.wrapMode = TextureWrapMode.Clamp;
            importer.textureCompression = TextureImporterCompression.Uncompressed;
            importer.npotScale = TextureImporterNPOTScale.None;
        }
    }
}
