using System.IO;
using UnityEditor;
using UnityEngine;

namespace Pets.EditorTools
{
    /// <summary>Applies the Sprite import settings the 9-sliced button/text-box art under
    /// Assets/Resources/Sprites/UI needs, the same way the rest of this project drives asset setup
    /// from code rather than hand-tuning import settings per file in the Inspector (see
    /// SceneBuilderUtils/the scene builders). Runs automatically whenever one of these textures is
    /// (re)imported.
    ///
    /// Every sprite in the folder is generated by tools/generate_ui_sprites.py to one shared
    /// 12x12 geometry with a 5px border, so a single set of numbers is correct for all of them —
    /// no per-file border table. Previously each file was a ~915x818 render of the same art with
    /// its own transparent padding, which is why the borders used to be per-file three-digit
    /// numbers that never quite lined up.</summary>
    public sealed class UiSpriteImportProcessor : AssetPostprocessor
    {
        private const string FolderPrefix = "Assets/Resources/Sprites/UI/";

        // The generated sprites are 12x12 with a 3-step chamfered corner; 5px covers the chamfer
        // plus the bevel ring, leaving a 2x2 flat centre to stretch. Keep in sync with SIZE/BORDER
        // in tools/generate_ui_sprites.py.
        private const float SpriteBorder = 5f;

        // On-screen border thickness = border / (spritePPU / canvas.referencePixelsPerUnit), so at
        // the default reference of 100 this draws each source pixel at exactly 2 canvas units —
        // a 10-unit border, which reproduces the proportions of the original art on a ~72-unit-tall
        // button. Keeping the scale an integer is what keeps the chamfer steps even under a Point
        // filter. (The old value of 20 went the wrong way: a *lower* PPU makes the border render
        // *larger*, which is how a 166px border ended up drawing ~830px wide on a 44px button.)
        private const float PixelsPerUnit = 50f;

        private void OnPreprocessTexture()
        {
            if (!assetPath.StartsWith(FolderPrefix) || Path.GetExtension(assetPath) != ".png")
            {
                return;
            }

            var importer = (TextureImporter)assetImporter;
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.spritePixelsPerUnit = PixelsPerUnit;
            importer.spriteBorder = new Vector4(SpriteBorder, SpriteBorder, SpriteBorder, SpriteBorder);
            importer.mipmapEnabled = false;

            // Point, not Bilinear: these are 12px-wide pixel-art sprites blown up ~2x and further
            // by the CanvasScaler. Bilinear turns the 1px outline and bevel into a smear, which is
            // most of why the art read as blurry rather than chunky.
            importer.filterMode = FilterMode.Point;
            importer.wrapMode = TextureWrapMode.Clamp;
            importer.alphaIsTransparency = true;

            // Block compression on a 12x12 sprite with hard 1px colour bands is all artifact and
            // no saving, and it bleeds neighbouring bands into each other along the bevel.
            importer.textureCompression = TextureImporterCompression.Uncompressed;
            importer.npotScale = TextureImporterNPOTScale.None;

            // FullRect is required for Image.Type.Sliced — a Tight mesh discards the transparent
            // corner area the 9-slice needs, so the chamfered corners tear when stretched.
            var settings = new TextureImporterSettings();
            importer.ReadTextureSettings(settings);
            settings.spriteMeshType = SpriteMeshType.FullRect;
            settings.spriteExtrude = 0;
            importer.SetTextureSettings(settings);
        }
    }
}
